### ISSUE TITLE
Give Credit?

### ISSUE THREAD

**Issue by mrsimonbennett** [odan/docblock-checker#4]
This project is based on https://github.com/Block8/php-docblock-checker which is fine and a good decision.  I am also aware they have not updated which is annoying (php 7.1 etc)

However, I notice no credit and you have edited the MIT licence file which @block8 / @dancryer may not appreciate. 

I would recommend at least giving credit

**Comment by odan** [comment]
Hi @mrsimonbennett Thank you for the feedback.  

I thank the original authors for this library and have just mentioned it under "Credits". I also adapted the license from MIT to BSD 2-Clause "Simplified".
